name: lbg-survey-strat
channels:
  - conda-forge
dependencies:
  - astropy
  - black
  - flake8
  - flake8-bugbear
  - flake8-simplify
  - isort
  - jupyterlab
  - matplotlib
  - mypy
  - numpy
  - pyccl
  - python=3.11
  - rubin-sim
  - tqdm
